
- name: Setup yazi
  vars:
    shell_utils_yazi_fullname: "{{ manifest.yazi.url | split('/') | last | split('.') | first }}"
    shell_utils_yazi_fullpath: "{{ home }}/.local/{{ shell_utils_yazi_fullname }}"
    shell_utils_yazi_path: "{{ home }}/.local/bin/yazi_dir"
  block:
    - name: Download yazi
      ansible.builtin.unarchive:
        src: "{{ manifest.yazi.url }}"
        dest: "{{ home }}/.local/"
        remote_src: true
      retries: "{{ web_retries }}"
      delay: "{{ web_delay }}"
      register: shell_utils_downloaded
      until: shell_utils_downloaded is not failed

    - name: Create symlink to yazi fullpath
      ansible.builtin.file:
        src: "{{ shell_utils_yazi_fullpath }}"
        dest: "{{ shell_utils_yazi_path }}"
        state: link

    - name: Create symlinks to yazi binaries
      ansible.builtin.file:
        src: "{{ shell_utils_yazi_fullpath }}/{{ item }}"
        dest: "{{ home }}/.local/bin/{{ item }}"
        state: link
      loop: [ya, yazi]

    - name: Create ~/.config/yazi directory
      ansible.builtin.file:
        dest: "{{ home }}/.config/yazi"
        state: directory
        mode: "0o755"

    # - name: Create symlink to yazi keymap
    #   ansible.builtin.file:
    #     src: "{{ role_host_path }}/files/yazi_keymap.toml"
    #     dest: "{{ home }}/.config/yazi/keymap.toml"
    #     state: link

    - name: Install more utils for yazi
      become: true
      ansible.builtin.package:
        name:
          - file
          - poppler-utils
          - poppler-data
          - unar