- name: Install lazygit
  ansible.builtin.unarchive:
    src: "{{ manifest.lazygit.url }}"
    dest: "{{ home }}/.local/bin"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: git_downloaded
  until: git_downloaded is not failed