- name: Install tmux packages
  become: true
  ansible.builtin.package:
    name:
      - tmux
      - python3-libtmux
  register: tmux_installed

- name: Install tmux-plugin-manager
  ansible.builtin.git:
    repo: "{{ manifest.tpm.url }}"
    dest: "{{ home }}/.tmux/plugins/tpm"
    version: "{{ manifest.tpm.version }}"
  register: tmux_downloaded
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  until: tmux_downloaded is not failed

# - name: Set up bash
#   ansible.builtin.lineinfile:
#     path: "{{ home }}/.bashrc"
#     regexp: "source .*/{{ role_name }}/files"
#     line: source {{ role_host_path }}/files/bash.sh
#   # Disable automatic tmux open for bash
#   when: false