apt_keys: /etc/apt/trusted.gpg.d # noqa: var-naming[no-role-prefix]
ubuntu_keyserver: https://keyserver.ubuntu.com/pks/lookup?op=get&search= # noqa: var-naming[no-role-prefix]

projects_host_path: "{{ home }}/projects" # noqa: var-naming[no-role-prefix]
dotfiles_host_parent_path: "{{ projects_host_path }}"
dotfiles_host_path: "{{ projects_host_path }}/dotfiles/ansible"
dotfiles_tmp_dir: "__artifacts__/tmp"
dotfiles_host_tmp: "{{ dotfiles_host_path }}/{{ dotfiles_tmp_dir }}"
role_host_path: "{{ dotfiles_host_path }}/roles/{{ role_name }}" # noqa: var-naming[no-role-prefix]