- name: Install common utils for other Ansible tasks
  become: true
  ansible.builtin.package:
    name:
      - curl
      - gnupg
      - patch
      - rsync
      - tzdata
      - unzip
      - xz-utils

- name: Install Ubuntu-specific common utils for other Ansible tasks
  become: true
  ansible.builtin.apt:
    name:
      - gpg-agent
      - locales
      - ntpdate
      - software-properties-common

- name: Set locale
  become: true
  community.general.locale_gen:
    name: "{{ profile.locale }}"

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ profile.timezone }}"

- name: Get user id
  ansible.builtin.getent:
    database: passwd
    key: "{{ ansible_user }}"

- name: Install hwclock for Ubuntu >= 23.10
  become: true
  ansible.builtin.package:
    name:
      - util-linux-extra
  when: ansible_distribution_version is version('23.10', '>=')
# - name: Check if inside container
#   ansible.builtin.shell: ([[ -f /.dockerenv || -f /run/.containerenv ]]) && echo true || echo false
#   args:
#     executable: bash
#   changed_when: false
#   register: basic_utils_container_out

- name: Set common facts
  ansible.builtin.set_fact:
    home: "{{ getent_passwd[ansible_user].4 }}"
    user_id: "{{ getent_passwd[ansible_user].1 }}"

    # web_delay: 15
    # web_retries: 3
    web_delay: 1
    web_retries: 2
  tags:
    - skip_ansible_lint

- name: Print detected facts
  ansible.builtin.debug:
    msg:
      - "home: {{ home }}"
      - "user: {{ ansible_user }}"
      - "user_id: {{ user_id }}"
      - "deb_arch: {{ deb_arch }}"