- hosts: localhost 
  vars:
    home_dir: "{{ ansible_env.HOME }}" 
    dotfiles_dir: "{{ playbook_dir }}/.."
    modules_dir: '{{ ansible_env.HOME }}/plugins/modules'
    common:
      - bash-completion
      - docker
      - tmux
      # - git
      # - tree
      # - watch
      # - wget
      # - zsh
  tasks:
  - name: Create ansible directory
    file: path={{ modules_dir }} state=directory
  - name: Symlink ansible hosts
    file:
      src: '{{ playbook_dir }}/hosts'
      dest: '{{ home_dir }}/hosts'
      state: link
      force: yes

  - name: Check if Docker is installed
    ansible.builtin.command: which docker
    register: docker_installed
    changed_when: false
    failed_when: false

  - name: Display a message if Docker is not installed
    ansible.builtin.debug:
      msg: "Docker is not installed on this system."
    when: docker_installed.rc != 0

  - name: Download docker shell script from get.docker.com
    when: docker_installed.rc != 0
    ansible.builtin.shell: 
      cmd: curl -fsSL https://get.docker.com -o get-docker.sh
    args:
      creates: get-docker.sh

  - name: Run get-docker.sh
    when: docker_installed.rc != 0
    ansible.builtin.shell: sh get-docker.sh

  - name: Setup usermod and groupadd docker
    when: docker_installed.rc != 0
    ansible.builtin.shell: 
      cmd: sudo usermod -aG docker $USER && sudo rm get-docker.sh

  - name: Installing tmux
    package:
      name: tmux
      state: present
    tags: tmux
    when: tmux_installed.rc != 0

  - name: Clone TPM repository
    git:
      repo: 'https://github.com/tmux-plugins/tpm.git'
      dest: /home/terrnit/.tmux/plugins/tpm
    become: true
    become_user: terrnit
    tags: tmux
    when: not tmp_installed.stat.exists
